### ISSUE TITLE
Cannot call method 'toString' of undefined/User info not passed to adapter.

### ISSUE THREAD

**Issue by hobblegobber** [nandub/hubot-irc#135]
Hello,

We have been trying to set up slack on hubot. We are following [this gist](https://gist.github.com/altryne/885ae98ea36dd7c897f7)

This is what is done so far:

1. Create hubot user on slack
2. launch hubot instance

```
HUBOT_IRC_NICK="ibot" \
HUBOT_IRC_SERVER="company.irc.slack.com" \
HUBOT_IRC_DEBUG=true \
HUBOT_IRC_PASSWORD="company.randompassword" \
HUBOT_IRC_ROOMS="#test,#general,#team-support" \
bin/hubot -a irc --name ibot
```

This launches the bot and we can see the user online. But, the bot throws out an error every time there is a message:

```
[Wed Nov 12 2014 10:45:54 GMT+0530 (IST)] ERROR TypeError: Cannot call method 'toString' of undefined
  at new User (/home/code/ibotv3/slack-ibot/node_modules/hubot/src/user.coffee:9:19, <js>:14:47)
  at Brain.userForId (/home/code/ibotv3/slack-ibot/node_modules/hubot/src/brain.coffee:106:7, <js>:93:16)
  at IrcBot.getUserFromId (/home/code/ibotv3/slack-ibot/node_modules/hubot-irc/src/irc.coffee:106:12, <js>:175:33)
  at IrcBot.createUser (/home/code/ibotv3/slack-ibot/node_modules/hubot-irc/src/irc.coffee:112:12, <js>:182:19)
  at Client.<anonymous> (/home/code/ibotv3/slack-ibot/node_modules/hubot-irc/src/irc.coffee:249:14, <js>:333:21)
  at Client.EventEmitter.emit (events.js:106:17)
  at Client.<anonymous> (/home/code/ibotv3/slack-ibot/node_modules/hubot-irc/node_modules/irc/lib/irc.js:471:22)
  at Client.EventEmitter.emit (events.js:95:17)
  at /home/code/ibotv3/slack-ibot/node_modules/hubot-irc/node_modules/irc/lib/irc.js:633:22
  at Array.forEach (native)
  at Socket.<anonymous> (/home/code/ibotv3/slack-ibot/node_modules/hubot-irc/node_modules/irc/lib/irc.js:630:15)
  at Socket.EventEmitter.emit (events.js:95:17)
  at Socket.<anonymous> (_stream_readable.js:746:14)
  at Socket.EventEmitter.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:408:10)
  at emitReadable (_stream_readable.js:404:5)
  at readableAddChunk (_stream_readable.js:165:9)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:526:21)
```

version info:

```
"dependencies": {
    "hubot": "^2.9.3",
    "hubot-diagnostics": "0.0.1",
    "hubot-google-images": "^0.1.0",
    "hubot-google-translate": "^0.1.0",
    "hubot-help": "^0.1.1",
    "hubot-heroku-keepalive": "0.0.4",
    "hubot-irc": "^0.2.7",
    "hubot-maps": "0.0.0",
    "hubot-pugme": "^0.1.0",
    "hubot-rules": "^0.1.0",
    "hubot-scripts": "^2.5.16",
    "hubot-shipit": "^0.1.1",
    "hubot-youtube": "^0.1.2"
  },
  "engines": {
    "node": "0.10.x"
  }
```

I can see that the `from` parameter is not passed on to the message listener

[relevant line](https://github.com/nandub/hubot-irc/blob/17c5d58799830f48dd0d0b215c0a9506139fddee/src/irc.coffee#L237)

Not sure if this is a problem on the slack's side or there is a bug in the adapter. Any help with debugging the issue would be appreciated.

**Comment by drafie** [comment]
I have the exact same error.

**Comment by shorrockin** [comment]
Just started getting this today after Hubot was working fine (through Slack) for the past few months. Nothing changed on Hu's end.

**Comment by radnor** [comment]
I'm also getting this error, and after setting `HUBOT_LOG_LEVEL` to `debug` it seems that the error is coming from the robot seeing its own message, or if a message comes from a user it can't parse.

This is the output from hubot using [hubot-jira-lookup](https://github.com/jivesoftware/hubot-jira-lookup) (triggering off my message `IT-3402`), then spitting out a message to the channel. When the script outputs through the robot the user is sent through as undefined:
```
[Thu Apr 30 2015 10:31:35 GMT-0700 (PDT)] INFO #discovery <kevin> yes
[Thu Apr 30 2015 10:31:35 GMT-0700 (PDT)] INFO #discovery <kevin> IT-3402
[Thu Apr 30 2015 10:31:35 GMT-0700 (PDT)] DEBUG Message 'IT-3402' matched regex //\b[A-Z]{2,5}-[0-9]{1,5}\b//
[Thu Apr 30 2015 10:31:37 GMT-0700 (PDT)] DEBUG From undefined to #discovery: Web servers full of mysterious event logs
[Thu Apr 30 2015 10:31:37 GMT-0700 (PDT)] ERROR TypeError: Cannot call method 'toString' of undefined
```
