### ISSUE TITLE
no method 'robot'

### ISSUE THREAD

**Issue by jordanbaucke** [nandub/hubot-irc#85]
I've seen this issue listed here before, but I'm having the same issue as well. Downloaded 2.3.2 release and added the dependencies, ran `npm install hubot-irc --save`, `npm install coffee-script --save`, and `npm install`

``` bash
2013-06-17T06:08:52.989801+00:00 heroku[app.1]: State changed from starting to up
2013-06-17T06:08:53.023127+00:00 app[app.1]: [Mon Jun 17 2013 06:08:53 GMT+0000 (UTC)] ERROR Cannot load adapter irc - TypeError: Object #<Object> has no method 'robot'
2013-06-17T06:08:53.023127+00:00 app[app.1]: TypeError: Object #<Object> has no method 'robot'
2013-06-17T06:08:53.023127+00:00 app[app.1]:   at Module._compile (module.js:446:26)
2013-06-17T06:08:53.023127+00:00 app[app.1]:   at Object.loadFile (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
2013-06-17T06:08:53.023127+00:00 app[app.1]:   at Function.Module._load (module.js:311:12)
2013-06-17T06:08:53.023127+00:00 app[app.1]:   at Object.<anonymous> (/app/node_modules/hubot-irc/src/irc.coffee:1:11, <js>:7:28)
2013-06-17T06:08:53.023127+00:00 app[app.1]:   at Object.<anonymous> (/app/node_modules/hubot-irc/src/irc.coffee:1:1, <js>:207:4)
2013-06-17T06:08:53.023127+00:00 app[app.1]:   at require (module.js:375:17)
2013-06-17T06:08:53.023368+00:00 app[app.1]:   at Module._compile (module.js:446:26)
2013-06-17T06:08:53.023127+00:00 app[app.1]:   at Module.load (/app/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:35)
2013-06-17T06:08:53.023368+00:00 app[app.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:80:11, <js>:79:19)
2013-06-17T06:08:53.023754+00:00 app[app.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:104:3, <js>:105:19)
2013-06-17T06:08:53.023754+00:00 app[app.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:11:1, <js>:109:4)
2013-06-17T06:08:53.023127+00:00 app[app.1]:   at Module.require (module.js:359:17)
2013-06-17T06:08:53.023368+00:00 app[app.1]: 
2013-06-17T06:08:53.023754+00:00 app[app.1]:   at Module._compile (module.js:446:26)
2013-06-17T06:08:53.023368+00:00 app[app.1]:   at Object.module.exports.loadBot (/app/node_modules/hubot/index.coffee:11:7, <js>:21:12)
2013-06-17T06:08:53.023368+00:00 app[app.1]:   at Object.<anonymous> (/app/node_modules/hubot/bin/hubot:11:1, <js>:109:4)
2013-06-17T06:08:53.023368+00:00 app[app.1]:   at Robot.loadAdapter (/app/node_modules/hubot/src/robot.coffee:230:7, <js>:217:31)
2013-06-17T06:08:53.023754+00:00 app[app.1]: TypeError: Cannot call method 'on' of null
2013-06-17T06:08:53.023368+00:00 app[app.1]:   at new Robot (/app/node_modules/hubot/src/robot.coffee:36:5, <js>:46:14)
2013-06-17T06:08:53.023754+00:00 app[app.1]: 
2013-06-17T06:08:54.194289+00:00 heroku[app.1]: Process exited with status 1
2013-06-17T06:08:54.214754+00:00 heroku[app.1]: State changed from up to crashed
```

Package.xml

``` json
{
  "name": "hosted-hubot",
  "version": "2.3.2",
  "author": "GitHub Inc.",
  "keywords": "github hubot campfire bot",
  "description": "A simple helpful Robot for your Company",
  "licenses": [
    {
      "type": "MIT",
      "url": "http://github.com/github/hubot/raw/master/LICENSE"
    }
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/github/hubot.git"
  },
  "dependencies": {
    "hubot": "2.3.2",
    "hubot-scripts": ">= 2.1.0",
    "optparse": "1.0.3",
    "hubot-irc": "0.0.8",
    "coffee-script": ">=1.0.0"
  },
  "engines": {
    "node": "0.6.x",
    "npm": "1.0.x"
  }
}
```

**Comment by chrisdotcode** [comment]
@jordanbaucke has not replied in 4 years, so let's assume this is fixed.

Feel free to comment if not.
